### ISSUE TITLE
Translate whole deck at once

### ISSUE THREAD

**Issue by maxlm128** [kelciour/deepl-translator#10]
Is there a way to translate a field from a whole deck at once? I hope that it is possible and that I just dont know how to do it, but I have a deck with 6000 Words and I would never translate each word one by clicking "translate" on each one.

**Comment by kelciour** [comment]
Yes, there is!

> select a few notes in the browser and click the Edit menu > DeepL Translator

![image](https://github.com/kelciour/deepl-translator/assets/16260735/d21d6812-72ad-40fa-8666-92a44c63ae96)

**Comment by maxlm128** [comment]
Thank you very much :)
