### ISSUE TITLE
Update for New Version of Anki

### ISSUE THREAD

**Issue by oscarhgriffin** [kelciour/deepl-translator#11]
Thank you so much for this add-on, it's saved me so much time with translating sentences. Sadly, it's currently broken with the new update. Just wanted to check and see if you're planning on an update. Much appreciated.

**Comment by nicknnnnnnn** [comment]
Hi Nickolay Nonard! Thank you for the add-on. Can you please update?

Here is the debug info:
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.23565

When loading DeepL Translator:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "C:\Users\***\***\Roaming\Anki2\addons21\972129549\__init__.py", line 11, in <module>
    from PyQt5.QtGui import QIcon
ModuleNotFoundError: No module named 'PyQt5'
