### ISSUE TITLE
Authentication Key doesn't work

### ISSUE THREAD

**Issue by faydanube** [kelciour/deepl-translator#13]
Deepl -> Account 

<img width="709" alt="image" src="https://github.com/kelciour/deepl-translator/assets/8817046/388dd683-8a11-4a90-8606-5558f2e388f5">

Here's the secret key I copied into the plugin to verify it doesn't work. I also searched the official documentation of the deepl api, and still couldn't find any other api key, so I'd like to ask what's wrong, thanks for sharing.

**Comment by kelciour** [comment]
It looks like the wrong key.

1. At first, sing up for DeepL API Free at https://www.deepl.com/pro-api

![image](https://github.com/kelciour/deepl-translator/assets/16260735/beb4afb7-6abf-4820-a670-bce55f2c6b50)

![image](https://github.com/kelciour/deepl-translator/assets/16260735/ea9e3d33-8272-4d32-baaf-fc07f58ca2bd)

![image](https://github.com/kelciour/deepl-translator/assets/16260735/34114a4e-560e-4a8b-8a9f-e289761b7843)

2. Then look for the API key.

> You need an authentication key to access the API. You can find your key in the ["API Keys" tab in your account](https://www.deepl.com/your-account/keys).
> DeepL API Free authentication keys can be identified easily by the suffix ":fx" (e.g., 279a2e9d-83b3-c416-7e2d-f721593e42a0:fx)
> 
> https://developers.deepl.com/docs/getting-started/auth#authentication
