### ISSUE TITLE
supress dialogue box

### ISSUE THREAD

**Issue by werowe** [kelciour/deepl-translator#14]
Hi.  Is there a way to supress the dialogue box.  Once you have configured it it should not ask each time the configuration information.  It should just do the translation with no dialogue box at all.  

I have this:

```
{
"API Key": "xxxxx",
"Overwrite": false,
"Source Field": "Front",
"Source Language": "Greek",
"Strip HTML": true,
"Target Field": "Back",
"Target Language": "English (American)"
}
```

**Comment by kelciour** [comment]
I've added it and updated the add-on on AnkiWeb.

![image](https://github.com/kelciour/deepl-translator/assets/16260735/22449097-5863-4a63-a7c7-9cf08ba6ed9f)
